'use client';

import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Checkbox } from '@/components/ui/checkbox';
import { Plus, Trash2, Copy, Download, Bot } from 'lucide-react';
import { toast } from 'sonner';

interface Rule {
  id: string;
  type: 'allow' | 'disallow';
  path: string;
}

export default function RobotsGeneratorPage() {
  const [userAgent, setUserAgent] = useState('*');
  const [rules, setRules] = useState<Rule[]>([
    { id: '1', type: 'allow', path: '/' },
    { id: '2', type: 'disallow', path: '/api/' },
    { id: '3', type: 'disallow', path: '/admin/' },
    { id: '4', type: 'allow', path: '/sitemap.xml' },
  ]);
  const [sitemapUrl, setSitemapUrl] = useState('https://www.example.com/sitemap.xml');
  const [crawlDelay, setCrawlDelay] = useState('');

  const addRule = () => {
    setRules([...rules, { id: Date.now().toString(), type: 'disallow', path: '' }]);
  };

  const removeRule = (id: string) => {
    setRules(rules.filter((r) => r.id !== id));
  };

  const updateRule = (id: string, field: keyof Rule, value: string) => {
    setRules(rules.map((r) => (r.id === id ? { ...r, [field]: value } : r)));
  };

  const generatedOutput = `# Robots.txt generated by Ytubeview
# https://www.example.com/robots.txt

User-agent: ${userAgent}

${rules.map((r) => `${r.type === 'allow' ? 'Allow' : 'Disallow'}: ${r.path}`).join('\n')}

${sitemapUrl ? `Sitemap: ${sitemapUrl}` : ''}${crawlDelay ? `\n\nCrawl-delay: ${crawlDelay}` : ''}`.trim();

  const copyOutput = () => {
    navigator.clipboard.writeText(generatedOutput);
    toast.success('Copied to clipboard!');
  };

  const downloadOutput = () => {
    const blob = new Blob([generatedOutput], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'robots.txt';
    a.click();
    URL.revokeObjectURL(url);
    toast.success('robots.txt downloaded!');
  };

  return (
    <div className="space-y-6">
      {/* User Agent */}
      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-base flex items-center gap-2">
            <Bot className="h-4 w-4 text-yt-red" />
            Robots.txt Generator
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-2">
            <Label>User-agent</Label>
            <div className="flex gap-2">
              <Input value={userAgent} onChange={(e) => setUserAgent(e.target.value)} placeholder="*" />
              <div className="flex gap-1">
                {['*', 'Googlebot', 'Bingbot'].map((agent) => (
                  <Button key={agent} variant="outline" size="sm" onClick={() => setUserAgent(agent)} className={userAgent === agent ? 'border-yt-red text-yt-red' : ''}>
                    {agent}
                  </Button>
                ))}
              </div>
            </div>
          </div>

          {/* Rules */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label>Crawl Rules</Label>
              <Button variant="ghost" size="sm" onClick={addRule}>
                <Plus className="h-4 w-4 mr-1" /> Add Rule
              </Button>
            </div>
            <div className="space-y-2">
              {rules.map((rule) => (
                <div key={rule.id} className="flex items-center gap-2">
                  <Button
                    variant={rule.type === 'allow' ? 'default' : 'outline'}
                    size="sm"
                    className={rule.type === 'allow' ? 'bg-yt-success hover:bg-yt-success/90 text-white w-20' : 'w-20'}
                    onClick={() => updateRule(rule.id, 'type', rule.type === 'allow' ? 'disallow' : 'allow')}
                  >
                    {rule.type === 'allow' ? 'Allow' : 'Disallow'}
                  </Button>
                  <Input
                    value={rule.path}
                    onChange={(e) => updateRule(rule.id, 'path', e.target.value)}
                    placeholder="/path/"
                    className="flex-1"
                  />
                  <Button variant="ghost" size="icon" className="text-red-500 hover:text-red-600" onClick={() => removeRule(rule.id)}>
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
              ))}
            </div>
          </div>

          {/* Sitemap + Crawl Delay */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label>Sitemap URL</Label>
              <Input value={sitemapUrl} onChange={(e) => setSitemapUrl(e.target.value)} placeholder="https://www.example.com/sitemap.xml" />
            </div>
            <div className="space-y-2">
              <Label>Crawl-delay (seconds, optional)</Label>
              <Input value={crawlDelay} onChange={(e) => setCrawlDelay(e.target.value)} placeholder="e.g., 10" type="number" />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Output Preview */}
      <Card>
        <CardHeader className="pb-2">
          <div className="flex items-center justify-between">
            <CardTitle className="text-base">Generated Output</CardTitle>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" onClick={copyOutput}>
                <Copy className="h-4 w-4 mr-1" /> Copy
              </Button>
              <Button variant="outline" size="sm" onClick={downloadOutput}>
                <Download className="h-4 w-4 mr-1" /> Download
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <pre className="bg-muted/50 rounded-lg p-4 text-sm font-mono overflow-x-auto border border-border/50">
            {generatedOutput}
          </pre>
        </CardContent>
      </Card>
    </div>
  );
}
